const ResponseStatusType = {
    OK: 'OK',
    BAD_REQUEST: 'BAD_REQUEST',
    UNAUTHORIZED: 'UNAUTHORIZED',
    VALIDATION_EXCEPTION: 'VALIDATION_EXCEPTION',
    EXCEPTION: 'EXCEPTION',
    WRONG_CREDENTIALS: 'WRONG_CREDENTIALS',
    ACCESS_DENIED: 'ACCESS_DENIED',
    NOT_FOUND: 'NOT_FOUND',
    DUPLICATE_ENTITY: 'DUPLICATE_ENTITY',
    WRONG_OTP: 'WRONG_OTP',
    OTP_HAS_LOCKED: 'OTP_HAS_LOCKED',
    BUSINESS_EXCEPTION: 'BUSINESS_EXCEPTION',
}
export default ResponseStatusType;